<script>
	import { darkMode } from '../lib/stores';
  
	let isDarkMode = false;

	// Subscribe to the darkMode store
	$: darkMode.subscribe((value) => {
		isDarkMode = value;
	});

	let message = 'PWA Cache';
</script>

<main
	class="flex flex-col items-center justify-center min-h-screen px-6 py-10"
	class:dark-mode={isDarkMode}
>
	<section class="text-center">
		<h1 class="mb-6 text-5xl font-extrabold tracking-tight leading-tight">{message}</h1>
		<div class="flex justify-center items-center mb-6">
			<img
				src="/icons/cloud-app.png"
				alt="Cloud App Logo"
				class="logo"
			/>
		</div>
		<p class="mb-12 text-lg max-w-xl mx-auto">
			This Progressive Web App (PWA) demonstrates advanced offline functionality using SvelteKit and Workbox. Enjoy
			seamless browsing with caching, offline support, and blazing-fast performance.
		</p>
		<a
			href="/posts"
			class="px-8 py-4 text-white bg-blue-600 rounded-lg shadow-md hover:bg-blue-700 transition text-lg font-semibold"
		>
			Explore Features
		</a>
	</section>

	<section class="mt-12 w-full max-w-4xl space-y-8">
		<!-- Key Features Card -->
		<div
			class="p-8 rounded-lg shadow-lg"
			style="background-color: var(--card-bg); color: var(--card-text);"
		>
			<h2 class="text-3xl font-bold text-center mb-6" style="color: var(--card-header);">
				Key Features
			</h2>
			<ul class="list-disc list-inside space-y-4 text-lg">
				<li>
					<strong>Offline Mode:</strong> Cache API responses and assets for uninterrupted access even without an internet
					connection.
				</li>
				<li>
					<strong>Workbox Integration:</strong> Optimized service worker strategies for caching and runtime management.
				</li>
				<li>
					<strong>Dynamic Caching:</strong> Fetch and cache API data to ensure the latest content is available offline.
				</li>
				<li>
					<strong>Modern UI:</strong> Responsive design with dark mode support for better user experience.
				</li>
			</ul>
		</div>

		<!-- Technical Overview Card -->
		<div
			class="p-8 rounded-lg shadow-lg"
			style="background-color: var(--card-bg); color: var(--card-text);"
		>
			<h2 class="text-3xl font-bold text-center mb-6" style="color: var(--card-header);">
				Technical Overview
			</h2>
			<div class="text-lg space-y-6">
				<p>
					This PWA uses a <strong>service worker</strong> generated by Workbox to enable offline access. Static assets,
					such as HTML, CSS, and JavaScript files, are cached using a <strong>Cache-First strategy</strong>, while API
					calls are handled with a <strong>Stale-While-Revalidate strategy</strong>.
				</p>
				<p>
					When offline, the app seamlessly serves cached API responses and static assets, ensuring uninterrupted
					functionality. The service worker lifecycle is optimized with <code>skipWaiting</code> and
					<code>clientsClaim</code> for immediate updates.
				</p>
				<div>
					<strong>Key Benefits:</strong>
					<ul class="list-disc list-inside mt-4">
						<li>Improved load times with cached assets.</li>
						<li>Enhanced reliability in low or no internet connectivity scenarios.</li>
						<li>Reduced server load due to intelligent caching.</li>
					</ul>
				</div>
			</div>
		</div>
	</section>
</main>

<style>
	:root {
		--light-bg: #f8fafc;
		--dark-bg: #1e293b;
		--card-bg-light: #2563eb;
		--card-text-light: white;
		--card-header-light: white;
		--card-bg-dark: white;
		--card-text-dark: black;
		--card-header-dark: #2563eb;
	}

	/* General Styles */
	main {
		font-family: 'Inter', sans-serif;
		background: var(--light-bg);
		color: #1f2937;
		transition: background 0.3s, color 0.3s;
	}

	h1 {
		color: #2563eb;
	}

	.logo {
		width: 200px;
		height: auto;
		margin: 20px 0; /* Equal top and bottom spacing */
	}

	a {
		display: inline-block;
		font-weight: bold;
		transition: transform 0.2s, background-color 0.2s;
	}

	a:hover {
		transform: translateY(-2px);
	}

	section {
		margin-bottom: 2rem;
	}

	/* Dark Mode */
	.dark-mode {
		background: var(--dark-bg);
		color: #f8fafc;
	}

	.dark-mode h1 {
		color: #2563eb;
	}

	/* Card Variables for Light Mode */
	:root {
		--card-bg: var(--card-bg-light);
		--card-text: var(--card-text-light);
		--card-header: var(--card-header-light);
	}

	/* Card Variables for Dark Mode */
	.dark-mode {
		--card-bg: var(--card-bg-dark);
		--card-text: var(--card-text-dark);
		--card-header: var(--card-header-dark);
	}
</style>
