<script>
	import FeatureCard from '$lib/components/FeatureCard.svelte';

	const cards = [
		{
			title: 'Key Features',
			content: `
				<ul class="list-disc list-inside space-y-4 text-lg">
					<li><strong>Offline Mode:</strong> Cache API responses and assets for uninterrupted access even without an internet connection.</li>
					<li><strong>Workbox Integration:</strong> Optimized service worker strategies for caching and runtime management.</li>
					<li><strong>Dynamic Caching:</strong> Fetch and cache API data to ensure the latest content is available offline.</li>
					<li><strong>Modern UI:</strong> Responsive design with dark mode support for better user experience.</li>
				</ul>
			`
		},
		{
			title: 'Technical Overview',
			content: `
				<p>
					This PWA uses a <strong>service worker</strong> generated by Workbox to enable offline access. Static assets, such as HTML, CSS, and JavaScript files, are cached using a <strong>Cache-First strategy</strong>, while API calls are handled with a <strong>Stale-While-Revalidate strategy</strong>.
				</p>
				<p>
					When offline, the app seamlessly serves cached API responses and static assets, ensuring uninterrupted functionality. The service worker lifecycle is optimized with <code>skipWaiting</code> and <code>clientsClaim</code> for immediate updates.
				</p>
				
				<br />

				<div>
					<strong>Key Benefits:</strong>
					<ul class="list-disc list-inside mt-4">
						<li>Improved load times with cached assets.</li>
						<li>Enhanced reliability in low or no internet connectivity scenarios.</li>
						<li>Reduced server load due to intelligent caching.</li>
					</ul>
				</div>
			`
		}
	];
</script>

<section class="mt-12 w-full max-w-4xl space-y-8">
	{#each cards as card (card.title)}
		<FeatureCard title={card.title} content={card.content} />
	{/each}
</section>